name: irc
kind: pipeline
type: exec

workspace:
  base: /project
  path: irc/

pipeline:
  test-1.14:
    image: golang:1.14
    group: tests
    commands:
      - go mod download
      - go test ./... -v
      - go test -bench ./...
  test-1.13:
    image: golang:1.13
    group: tests
    commands:
      - go mod download
      - go test ./... -v
      - go test -bench ./...
  test-1.12:
    image: golang:1.12
    group: tests
    commands:
      - go mod download
      - go test ./... -v
      - go test -bench ./...
  test-1.11:
    image: golang:1.11
    group: tests
    commands:
      - go mod download
      - go test ./... -v
      - go test -bench ./...
  test-1.10:
    image: golang:1.10
    group: tests
    commands:
      - mkdir -p /go/src/github.com/gissleh/
      - ln -s /project/irc /go/src/github.com/gissleh/irc
      - cd /go/src/github.com/gissleh/irc/
      - ls -lR
      - go test ./... -v
      - go test -bench ./...
  test-1.9:
    image: golang:1.9
    group: tests
    commands:
      - mkdir -p /go/src/github.com/gissleh/
      - ln -s /project/irc /go/src/github.com/gissleh/irc
      - cd /go/src/github.com/gissleh/irc/
      - go test ./... -v
      - go test -bench ./...
  test-1.8:
    image: golang:1.8
    group: tests
    commands:
      - mkdir -p /go/src/github.com/gissleh/
      - ln -s /project/irc /go/src/github.com/gissleh/irc
      - cd /go/src/github.com/gissleh/irc/
      - go test ./... -v
      - go test -bench ./...