name: irc
kind: pipeline
type: exec

workspace:
  base: /project
  path: irc/

pipeline:
  test:
    name: test-go-${GO_VERSION}
    image: golang:${GO_VERSION}
    commands:
      - go mod download
      - go test ./... -v
      - go test -bench ./...

matrix:
  GO_VERSION:
   - "1.11"
   - "1.12"
   - "1.13"
   - "1.14"
