workspace:
  base: /go
  path: src/github.com/gissleh/irc

pipeline:
  test:
    image: golang:${GO_VERSION}
    commands:
      - go test ./... -v
      - go test -bench ./...

matrix:
  GO_VERSION:
   - "1.11"
   - "1.10"
   - "1.9"
   - "1.8"
